from .oc_character_block import (
    OCCharacterAccessoriesBlockNode,
    OCCharacterBodyBlockNode,
    OCCharacterFaceBlockNode,
    OCCharacterHairBlockNode,
    OCCharacterOutfitBlockNode,
)
from .oc_generator import OCGeneratorNode
from .oc_merge_block import OCBlockMergeNode
from .oc_outfit_part_nodes import (
    OCOutfitDecorationPartNode,
    OCOutfitFacewearPartNode,
    OCOutfitFootwearPartNode,
    OCOutfitHandwearPartNode,
    OCOutfitHeadwearPartNode,
    OCOutfitJewelryPartNode,
    OCOutfitLegwearPartNode,
    OCOutfitNeckwearPartNode,
    OCOutfitOuterPartNode,
    OCOutfitPantsPartNode,
    OCOutfitSkirtPartNode,
    OCOutfitStylePartNode,
    OCOutfitUpperPartNode,
    OCOutfitWaistPartNode,
)
from .oc_theme_block import OCThemeBlockNode


NODE_CLASS_MAPPINGS = {
    "OCGeneratorNode": OCGeneratorNode,
    "OCThemeBlockNode": OCThemeBlockNode,
    "OCCharacterBodyBlockNode": OCCharacterBodyBlockNode,
    "OCCharacterFaceBlockNode": OCCharacterFaceBlockNode,
    "OCCharacterHairBlockNode": OCCharacterHairBlockNode,
    "OCCharacterAccessoriesBlockNode": OCCharacterAccessoriesBlockNode,
    "OCCharacterOutfitBlockNode": OCCharacterOutfitBlockNode,
    "OCBlockMergeNode": OCBlockMergeNode,
    "OCOutfitStylePartNode": OCOutfitStylePartNode,
    "OCOutfitUpperPartNode": OCOutfitUpperPartNode,
    "OCOutfitOuterPartNode": OCOutfitOuterPartNode,
    "OCOutfitPantsPartNode": OCOutfitPantsPartNode,
    "OCOutfitSkirtPartNode": OCOutfitSkirtPartNode,
    "OCOutfitLegwearPartNode": OCOutfitLegwearPartNode,
    "OCOutfitFootwearPartNode": OCOutfitFootwearPartNode,
    "OCOutfitNeckwearPartNode": OCOutfitNeckwearPartNode,
    "OCOutfitHandwearPartNode": OCOutfitHandwearPartNode,
    "OCOutfitWaistPartNode": OCOutfitWaistPartNode,
    "OCOutfitHeadwearPartNode": OCOutfitHeadwearPartNode,
    "OCOutfitFacewearPartNode": OCOutfitFacewearPartNode,
    "OCOutfitJewelryPartNode": OCOutfitJewelryPartNode,
    "OCOutfitDecorationPartNode": OCOutfitDecorationPartNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "OCGeneratorNode": "OC Generator",
    "OCThemeBlockNode": "OC Theme Block",
    "OCCharacterBodyBlockNode": "OC Character Body Block",
    "OCCharacterFaceBlockNode": "OC Character Face Block",
    "OCCharacterHairBlockNode": "OC Character Hair Block",
    "OCCharacterAccessoriesBlockNode": "OC Character Accessories Block",
    "OCCharacterOutfitBlockNode": "OC Character Outfit Block",
    "OCBlockMergeNode": "OC Block Merge",
    "OCOutfitStylePartNode": "OC Outfit Style Part",
    "OCOutfitUpperPartNode": "OC Outfit Upper Part",
    "OCOutfitOuterPartNode": "OC Outfit Outer Part",
    "OCOutfitPantsPartNode": "OC Outfit Pants Part",
    "OCOutfitSkirtPartNode": "OC Outfit Skirt Part",
    "OCOutfitLegwearPartNode": "OC Outfit Legwear Part",
    "OCOutfitFootwearPartNode": "OC Outfit Footwear Part",
    "OCOutfitNeckwearPartNode": "OC Outfit Neckwear Part",
    "OCOutfitHandwearPartNode": "OC Outfit Handwear Part",
    "OCOutfitWaistPartNode": "OC Outfit Waist Part",
    "OCOutfitHeadwearPartNode": "OC Outfit Headwear Part",
    "OCOutfitFacewearPartNode": "OC Outfit Facewear Part",
    "OCOutfitJewelryPartNode": "OC Outfit Jewelry Part",
    "OCOutfitDecorationPartNode": "OC Outfit Decoration Part",
}
